language: go
go:
   - 1.2
   - 1.3
   - 1.4
   - 1.5
   - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - go get github.com/arachnist/gorepost/bot
    - go get github.com/arachnist/gorepost/irc
    - go get github.com/arachnist/gorepost/config
script:
   - go test -v
matrix:
  allow_failures:
      - go: 1.0
      - go: 1.1
