language: go
go:
   - 1.0
   - 1.1
   - 1.2
   - 1.3
   - 1.4
   - 1.5
   - tip
script:
   - go test -v
go_import_path:
    - github.com/arachnist/gorepost/bot
    - github.com/arachnist/gorepost/irc
    - github.com/arachnist/gorepost/config
matrix:
  allow_failures:
      - go: 1.0
      - go: 1.1
