language: go
go:
   - 1.5
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
sudo: required
dist: trusty
notifications:
    irc: "chat.freenode.net#gorepost-test"
before_install:
    - go get github.com/arachnist/gorepost/bot
    - go get github.com/arachnist/gorepost/irc
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get github.com/go-playground/overalls
    - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
    - echo "deb http://pl.archive.ubuntu.com/ubuntu trusty main restricted universe multiverse" | sudo tee /etc/apt/sources.list
    - echo "deb http://pl.archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
    - echo "deb http://pl.archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y kyototycoon
before_script:
    - ktserver -dmn -host 127.0.0.1 -port 1337
script:
    - go test -race -v ./...
    - $HOME/gopath/bin/overalls -project=github.com/arachnist/gorepost -covermode=count -debug
    - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
